### ISSUE TITLE
Create the Search Page

### ISSUE THREAD

**Issue by zehro** [zehro/UAH-Theatre#23]
## Description
There needs to be a UI page for searching the inventory.

## Tasks
- [x] Create UI page
- [x] Code back-end logic

## Done Done Criteria
1. The page is tested and accepted by at least one other team member
2. The code is reviewed and passed any unit/acceptance tests
3. The code is merged with master branch

**Comment by ghost** [comment]
I believe the search page and the search result page should actually be the same page (using the same template). It's just that the DOM is updated and different data is shown based on the filter query. If you are already working on this task, I'll leave a comment on the other task and work on the item detail page instead.
