### ISSUE TITLE
Choose a Database Hosting Service

### ISSUE THREAD

**Issue by mjohnson342** [zehro/UAH-Theatre#25]
## Description
We need to determine how UAH will host their app, as according to Issue #24. Then we need to choose one that is most appropriate.

## Tasks
- [x] Find out if UAH has private servers or if we need to choose a different service

## Done Done Criteria
1. The team has received an email about their hosting service capabilities
2. The team agrees by consensus on the future hosting service

**Comment by zehro** [comment]
@mjohnson342 I have updated the issue description. Make sure that the issue follows the example templates when making future issues.

**Comment by zehro** [comment]
We are currently working with Google Cloud Platform, but that most likely won't be the client's production server. @mjohnson342 needs to finalize on the details regarding what service the client will use and write a report.
