### ISSUE TITLE
Create the Search Result Page

### ISSUE THREAD

**Issue by zehro** [zehro/UAH-Theatre#9]
## Description
There needs to be a UI page for search results.

## Tasks
- [x] Create UI page
- [x] Code back-end logic

## Done Done Criteria
1. The page is tested and accepted by at least one other team member
2. The code is reviewed and passed any unit/acceptance tests
3. The code is merged with master branch

**Comment by ghost** [comment]
The search page and the search result page should actually be the same page (using the same template). It's just that the DOM is updated and different data is shown based on the filter query. Merge this task with #23
